### ISSUE TITLE
Jade renamed to Pug

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [gruntjs/grunt-contrib-jade#160] opened 2016-04-10 00:04 UTC
Since Jade is being renamed to Pug, will this repo change names as well?
https://github.com/pugjs/pug/issues/2184

**Comment by shinnn** [comment] 2016-04-11 07:03
Thanks for the issue report, but just a duplicate of https://github.com/gruntjs/grunt-contrib-jade/issues/156.

Recently @vladikoff thoughtlessly closed all opened issues.

**Closed by shinnn** 2016-04-11 07:03 UTC
